# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"\"\n\nLogRequest\x12\x14\n\x0cprocess_name\x18\x01 \x01(\t\"0\n\x08LogEntry\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0bline_number\x18\x02 \x01(\x05\x32H\n\nLogService\x12:\n\nStreamLogs\x12\x15.streaming.LogRequest\x1a\x13.streaming.LogEntry0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=30
  _globals['_LOGREQUEST']._serialized_end=64
  _globals['_LOGENTRY']._serialized_start=66
  _globals['_LOGENTRY']._serialized_end=114
  _globals['_LOGSERVICE']._serialized_start=116
  _globals['_LOGSERVICE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
